nextflow run main.nf \
    -profile docker \
    --skip_fetch_data true \
    --skip_star_genome true \
    --input data/samplesheet.csv \
    --fastq_out data \
    --spatial_barcodes data/references/spatial_barcodes.txt \
    --ref_map data/references/Mus_musculus/Ensembl/GRCm38/Sequence/star \
    --ref_annotation data/references/Mus_musculus/Ensembl/GRCm38/Annotation/Genes/genes.gtf \
    --ref_atac_genome data/references/Mus_musculus/refdata-cellranger-atac-mm10-1.2.0.tar.gz \
    --outdir result \
    -resume 2>&1 | tee headnode.log